"""update

Revision ID: 0b4de551712b
Revises: 28f5f63d72b5
Create Date: 2024-03-05 23:26:00.402781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4de551712b'
down_revision = '28f5f63d72b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yazilar', schema=None) as batch_op:
        batch_op.alter_column('kategori',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yazilar', schema=None) as batch_op:
        batch_op.alter_column('kategori',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
