"""update

Revision ID: 0ed4380c7ef2
Revises: 
Create Date: 2024-03-03 10:32:32.277249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed4380c7ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yazilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yazilar')
    # ### end Alembic commands ###
