"""update

Revision ID: df53bcfefb65
Revises: 0ed4380c7ef2
Create Date: 2024-03-03 10:33:50.173692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df53bcfefb65'
down_revision = '0ed4380c7ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yazilar', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yazilar', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###
